version: "3"
services:
  mongo:
    image: mongo:4.1
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin01
      - MONGO_INITDB_DATABASE=account-manager

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
