version: "3"
services:
  mongo:
    image: mongo:4.1
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: mongo
      MONGODB_PASS: mongo01

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
